export const FETCH_OPERATIONCURRENCIES_REQUEST =
  "FETCH_OPERATIONCURRENCIES_REQUEST";
export const FETCH_OPERATIONCURRENCIES_SUCCESS =
  "FETCH_OPERATIONCURRENCIES_SUCCESS";
export const FETCH_OPERATIONCURRENCIES_FAILURE =
  "FETCH_OPERATIONCURRENCIES_FAILURE";
export const SET_GLOBAL_CURRENCY = "SET_GLOBAL_CURRENCY";
